spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1
    username: root
    password: arindam
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: order-service
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: order-events
server:
  port: 1003